version: "3"
services:
  app:
    build: .
    container_name: advance_todo_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: container_name
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
